global:
  domain: <DOMAIN_NAME>
  imagePullSecret:
    name: blank
srv:
  bindings:
    uaa:
      serviceInstanceName: xsuaa
    db:
      fromSecret: <DB_SECRET_NAME>
    destinations:
      serviceInstanceName: destinations
    messaging:
      serviceInstanceName: event-mesh
  image:
    repository: <DOCKER_REPOSITORY>/kyma-cap-s4ems-srv
    tag: latest
  resources:
    limits:
      cpu: 100m
      ephemeral-storage: 1G
      memory: 500M
    requests:
      cpu: 100m
      ephemeral-storage: 1G
      memory: 500M
  health_check:
    liveness:
      path: /
    readiness:
      path: /
  additionalVolumes:
    - name: connectivity-secret
      volumeMount:
        mountPath: /bindings/connectivity
        readOnly: true
      projected:
        sources:
          - secret:
              name: <RELEASE_NAME>-connectivity-binding
              optional: false
          - secret:
              name: <RELEASE_NAME>-connectivity-binding
              optional: false
              items:
                - key: token_service_url
                  path: url
          - configMap:
              name: <RELEASE_NAME>-connectivity-proxy-info
              optional: false
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: <RELEASE_NAME>
  config: xs-security.json
hana_deployer:
  image:
    repository: <DOCKER_REPOSITORY>/kyma-cap-s4ems-db
    tag: latest
  bindings:
    hana:
      fromSecret: caphana
connectivity:
  serviceOfferingName: connectivity
  servicePlanName: connectivity_proxy
  secretName: <RELEASE_NAME>-connectivity-binding
  configMapName: <RELEASE_NAME>-connectivity-proxy-info
destinations:
  serviceOfferingName: destination
  servicePlanName: lite
  parameters:
    version: 1.0.0
    HTML5Runtime_enabled: true
event_mesh:
  serviceOfferingName: enterprise-messaging
  servicePlanName: default
  config: event-mesh.json
html5_apps_deployer:
  cloudService: com.bp.businesspartners
  backendDestinations:
    srv-binding: 
      service: srv
  image:
    repository: <DOCKER_REPOSITORY>/kyma-cap-s4ems-html5-deployer
    tag: latest
  bindings:
    xsuaa:
      serviceInstanceName: xsuaa
    destination:
      serviceInstanceName: destinations
    html5_apps_repo:
      serviceInstanceName: html5-apps-repo-host
html5_apps_repo_host:
  serviceOfferingName: html5-apps-repo
  servicePlanName: app-host

gitusername: <base64encodeduser>
gitpassword: <base_64_encoded_GIT_secret>
giturl: <git_repo_url>
gitbranch: <branch>

functionshttpproxy: https://connectivity-proxy.kyma-system.svc.cluster.local:20003
functionsenv: '{ "name":"s4h", "attachmentSrvApi":"API_CV_ATTACHMENT_SRV", "businessPartnerSrvApi":"API_BUSINESS_PARTNER", "businessObjectTypeName" : "BUS1006" }'
