apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: {{ .Release.Name }}-caphana
spec:
  serviceOfferingName: hana
  servicePlanName: hdi-shared
  externalName: hdi-shared-instance

---

apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceBinding
metadata:
  name: {{ .Release.Name }}-caphana-binding
spec:
  serviceInstanceName: {{ .Release.Name }}-caphana
  externalName: {{ .Release.Name }}-caphana
  secretName: {{ .Release.Name }}-caphana
