apiVersion: serverless.kyma-project.io/v1alpha1
kind: GitRepository
metadata:
  name: {{ .Release.Name }}-qrcodegenerator
  namespace: {{.Values.namespace}}
  labels:
     name: kyma-cap-s4ems
spec:
  url: {{.Values.giturl}}
  auth:
    type: basic
    secretName: {{ .Release.Name }}-githubtools