
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: {{ .Release.Name }}-xsuaademo
  namespace: {{.Values.namespace}}
spec:
  clusterServiceClassExternalName: xsuaa
  clusterServicePlanExternalName: application
  parameters:
    xsappname: {{ .Release.Name }}-BusinessPartnerValidation
    tenant-mode: dedicated
    oauth2-configuration:
      redirect-uris:
        - https://*/**

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-emdemo
  namespace: {{.Values.namespace}}
type: opaque
stringData: 
  emsecret: >
     {{.Values.emsecret}}


---

apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: {{ .Release.Name }}emdemo
  namespace: {{.Values.namespace}}
spec: 
  clusterServiceClassExternalName: enterprise-messaging
  clusterServicePlanExternalName: default
  parametersFrom: 
    - secretKeyRef: 
        name: {{ .Release.Name }}-emdemo
        key: emsecret

---

apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: {{ .Release.Name }}-destdemo
  namespace: {{.Values.namespace}}
spec: 
  clusterServiceClassExternalName: destination
  clusterServicePlanExternalName: lite

---

apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: {{ .Release.Name }}-conndemo
  namespace: {{.Values.namespace}}
spec: 
  clusterServiceClassExternalName: connectivity
  clusterServicePlanExternalName: connectivity_proxy


    
