
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: {{ .Release.Name }}-kymacap-xsuaademo
  namespace: amit
  labels:
    app.kubernetes.io/name: kyma-cap-s4ems
spec:
  externalName: ''
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: kymacap-BusinessPartnerValidation
    tenant-mode: dedicated
    oauth2-configuration: 
      redirect-uris: 
      - https://*/**

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-kymacap-emdemo
  labels:
    app.kubernetes.io/name: kyma-cap-s4ems
  annotations: {}
stringData: 
  emsecret: >
     {{.Values.emsecret}}


---

apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: {{ .Release.Name }}-kymacapemdemo
  namespace: amit
  labels:
    app.kubernetes.io/name: kyma-cap-s4ems
spec:
  externalName: ''
  serviceOfferingName: enterprise-messaging
  servicePlanName: default
  parameters:
    {{.Values.emsecret}}

---

apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: {{ .Release.Name }}-kymacap-destdemo
  namespace: amit
  labels:
    app.kubernetes.io/name: kyma-cap-s4ems
spec:
  externalName: ''
  serviceOfferingName: destination
  servicePlanName: lite
  parameters: {}

---

apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: {{ .Release.Name }}-kymacap-conndemo
  namespace: amit
  labels:
    app.kubernetes.io/name: kyma-cap-s4ems
spec:
  externalName: ''
  serviceOfferingName: connectivity
  servicePlanName: connectivity_proxy
  parameters: {}


    
