apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hana-secret
  namespace: {{.Values.namespace}}
  labels:
     name: kyma-cap-s4ems
type: opaque
stringData: 
  hana-credentials: >
         {{.Values.hanacredentials}}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kymahdi
  labels:
    app: {{ .Release.Name }}-kymahdi
    version: v1
    name: kyma-cap-s4ems
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kymahdi
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kymahdi
        version: v1
        name: kyma-cap-s4ems
    spec:
      containers:
      - name: {{ .Release.Name }}-kymahdi
        image: {{.Values.hdiimage}}
        resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
        imagePullPolicy: Always
        ports:
        - containerPort: 4004
        env:
          - name: HANA_CREDENTIALS
            valueFrom:
              secretKeyRef:
                  name: {{ .Release.Name }}-hana-secret
                  key: hana-credentials
          - name: VCAP_SERVICES
            value: >
              {
                "hana": [
                  {
                    "name": "cpapp-kyma-hdi",
                    "tags": [
                      "hana"
                    ],
                    "credentials": $(HANA_CREDENTIALS)
                  }
                ]
              }