apiVersion: v1
kind: Secret
metadata:
  name: hana-secret
  namespace: demo
type: opaque
stringData: 
  hana-credentials: >
         {{.Values.hanacredentials}}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kymahdi
  labels:
    app: kymahdi
    version: v1
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kymahdi
      version: v1
  template:
    metadata:
      labels:
        app: kymahdi
        version: v1
    spec:
      containers:
      - name: kymahdi
        image: docker-registrynew.d6c9019.kyma-stage.shoot.live.k8s-hana.ondemand.com/kymahdi
        resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
        imagePullPolicy: Always
        ports:
        - containerPort: 4004
        env:
          - name: HANA_CREDENTIALS
            valueFrom:
              secretKeyRef:
                  name: hana-secret
                  key: hana-credentials
          - name: VCAP_SERVICES
            value: >
              {
                "hana": [
                  {
                    "name": "cpapp-kyma-hdi",
                    "tags": [
                      "hana"
                    ],
                    "credentials": $(HANA_CREDENTIALS)
                  }
                ]
              }