
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-approuterkymaui
  labels:
    app: {{ .Release.Name }}-approuterkymaui
    name: kyma-cap-s4ems
    version: v1
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-approuterkymaui
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-approuterkymaui
        name: kyma-cap-s4ems
        version: v1
    spec:
      containers:
      - name: {{ .Release.Name }}-approuterkymaui
        image: docker-registrynew.d6c9019.kyma-stage.shoot.live.k8s-hana.ondemand.com/kymademoui
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: xsuaa-volume
          mountPath: "/etc/secrets/sapcp/xsuaa/xsuaaInst"
          readOnly: true
        env:
        - name: destinations
          value: '[ {"name":"srv-binding", "url":"https://grs-kymacap.d6c9019.kyma-stage.shoot.live.k8s-hana.ondemand.com","forwardAuthToken": true }]'
      volumes:
      - name: xsuaa-volume
        secret:
          secretName: {{ .Release.Name }}-xsuaa-binding
       
          

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-approuterkymaui
  namespace: {{.Values.namespace}}
  labels:
    name: kyma-cap-s4ems
    app: {{ .Release.Name }}-approuterkymaui
    service: {{ .Release.Name }}-approuterkymaui
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: {{ .Release.Name }}-approuterkymaui

---

apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  namespace: {{.Values.namespace}}
  labels:
    name: kyma-cap-s4ems
    app: {{ .Release.Name }}-approuterkymaui
  name: {{ .Release.Name }}-approuterkymaui
spec:
  service:
    host: {{ .Release.Name }}-approuterkymaui
    name: {{ .Release.Name }}-approuterkymaui
    port: 5000
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      methods: ["GET", "PUT", "POST", "HEAD", "PATCH", "DELETE" ]
      mutators:
        - config:
            headers:
              x-forwarded-host: >-
                grs-approuterkymaui.d6c9019.kyma-stage.shoot.live.k8s-hana.ondemand.com
              x-forwarded-proto: https
          handler: header
      accessStrategies:
        - handler: noop