apiVersion: v1
kind: Secret
metadata:
  name: hana-secret
  namespace: gopal
type: opaque
stringData: 
  hana-credentials: >
         {
            "url": "jdbc:sap://50617b3e-cdd3-45bb-9612-ed0da6cebea8.hana.canary-eu10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=52293B0F446548618F266F4D70DA1AA2",
            "certificate": "-----BEGIN CERTIFICATE-----\nMIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh\nMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\nd3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD\nQTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT\nMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j\nb20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG\n9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB\nCSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97\nnh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt\n43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P\nT19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4\ngdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO\nBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR\nTLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw\nDQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr\nhMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg\n06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF\nPnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls\nYSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk\nCAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=\n-----END CERTIFICATE-----",
            "driver": "com.sap.db.jdbc.Driver",
            "hdi_password": "Vz0v_7aouB4R0f.PUmDpLV_fmW7NLFfkNu3s6Jmux8gSTx6nEiW_EO7Rc1LBfueQD7fPvBHUJn5XhxSgKaXzwMGG90.EILSnSYKFJ.Vr-_Vmah2MQ05xUdUSz3tRWL1k",
            "hdi_user": "52293B0F446548618F266F4D70DA1AA2_3YRWYFQIIOOB5C5F71D6ZTRV4_DT",
            "host": "50617b3e-cdd3-45bb-9612-ed0da6cebea8.hana.canary-eu10.hanacloud.ondemand.com",
            "password": "Lt4JO3vskhGtdSr0Id8LTND7xg4TpMbiDW1WLxYf.NL5lKEvRX6rO3IV8cHMYH2MB7JJuQW863R5gjlWewIVp28ET7E3jTyvjzbEXQrwoQuP0corSMDhdMTsUMRHO66j",
            "port": "443",
            "schema": "52293B0F446548618F266F4D70DA1AA2",
            "user": "52293B0F446548618F266F4D70DA1AA2_3YRWYFQIIOOB5C5F71D6ZTRV4_RT"
         }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kymahdi
  labels:
    app: kymahdi
    version: v1
  namespace: gopal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kymahdi
      version: v1
  template:
    metadata:
      labels:
        app: kymahdi
        version: v1
    spec:
      containers:
      - name: kymahdi
        image: gopalanand/kymahdi:latest
        resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
        imagePullPolicy: Always
        ports:
        - containerPort: 4004
        env:
          - name: HANA_CREDENTIALS
            valueFrom:
              secretKeyRef:
                  name: hana-secret
                  key: hana-credentials
          - name: VCAP_SERVICES
            value: >
              {
                "hana": [
                  {
                    "name": "cpapp-kyma-hdi",
                    "tags": [
                      "hana"
                    ],
                    "credentials": $(HANA_CREDENTIALS)
                  }
                ]
              }