
#specifies values for HANA secret
messagingsecret: '{
    "emClientId": "s4c1",
    "systemName": "grss4hanacloud"
   }'

hanacredentials: '{
            "url": "jdbc:sap://930653ef-22d9-46ea-ab5e-5856ee2e107f.hana.prod-eu20.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=16FD9AFD29DF4EC1AE95EA3A8C043015",
            "certificate": "-----BEGIN CERTIFICATE-----\nMIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh\nMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\nd3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD\nQTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT\nMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j\nb20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG\n9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB\nCSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97\nnh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt\n43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P\nT19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4\ngdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO\nBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR\nTLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw\nDQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr\nhMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg\n06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF\nPnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls\nYSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk\nCAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=\n-----END CERTIFICATE-----",
            "driver": "com.sap.db.jdbc.Driver",
            "hdi_password": "Kf3YZgeMmUMPL-n2vxApEZ8HHEnJbAX2r1IO2PZPd8YiAEKNj.LS-o_oW.PDn2fhnTbX.hF5b6NdzWGC-9J7bq3iO0dMTmZKgkJ8viWEJrZ1QqWD40hohMTajVLBSnq3",
            "hdi_user": "16FD9AFD29DF4EC1AE95EA3A8C043015_56SNXBIODY7UE4P9DLHTLFVVW_DT",
            "host": "930653ef-22d9-46ea-ab5e-5856ee2e107f.hana.prod-eu20.hanacloud.ondemand.com",
            "password": "Xh8IlluxuMMuPYyU3ywe-aIWI07tFGnc5fBBYJ-43042h6.t423qjjrDPpfiWZWWLJGuzL22fLWEDFEc4BBmkrvTosdvx00zbggLBAeSNm90b2AAJgCqjQUOzWmz8wai",
            "port": "443",
            "schema": "16FD9AFD29DF4EC1AE95EA3A8C043015",
            "user": "16FD9AFD29DF4EC1AE95EA3A8C043015_56SNXBIODY7UE4P9DLHTLFVVW_RT"
          }'

apiaccesssecret: '{
	  "systemName": "grss4hanacloud",
	  "communicationArrangement": {
	    "communicationArrangementName": "s4c1",
	    "scenarioId": "SAP_COM_0008",
	    "inboundAuthentication": "BasicAuthentication",
	    "outboundAuthentication": "BasicAuthentication",
	    "outboundServices": [
	      {
	        "name": "Replicate Customers from S/4 System to Client",
	        "isServiceActive": false
	      },
	      {
	        "name": "Replicate Suppliers from S/4 System to Client",
	        "isServiceActive": false
	      },
	      {
	        "name": "Replicate Company Addresses from S/4 System to Client",
	        "isServiceActive": false
	      },
	      {
	        "name": "Replicate Workplace Addresses from S/4 System to Client",
	        "isServiceActive": false
	      },
	      {
	        "name": "Replicate Personal Addresses from S/4 System to Client",
	        "isServiceActive": false
	      },
	      {
	        "name": "Business Partner - Replicate from SAP S/4HANA Cloud to Client",
	        "isServiceActive": false
	      },
	      {
	        "name": "Business Partner Relationship - Replicate from SAP S/4HANA Cloud to Client",
	        "isServiceActive": false
	      },
	      {
	        "name": "Business Partner - Send Confirmation from SAP S/4HANA Cloud to Client",
	        "isServiceActive": false
	      },
	      {
	        "name": "BP Relationship - Send Confirmation from SAP S/4HANA Cloud to Client",
	        "isServiceActive": false
	      }
	    ],
	    "communicationSystem": {
	      "communicationSystemHostname": "https://default.com",
	      "outboundCommunicationUser": {
	        "username": "DefaultUser",
	        "password": "DefaultPassword"
	      }
	    }
	  }
	}'

emsecret: '{
        "emname": "ccdemogr",
        "namespace": "refapps/ccdemogr/event",
        "options": {
          "management": true,
          "messaging": true,
          "messagingrest": true
        },
        "rules": {
          "queueRules": {
            "publishFilter": [
            "${namespace}/*"
          ],
          "subscribeFilter": [
            "${namespace}/*",
            "sap/S4HANAOD/s4c1/*"
          ]
        },
        "topicRules": {
          "publishFilter": [
          "${namespace}/*"
        ],
        "subscribeFilter": [
          "${namespace}/*",
          "sap/S4HANAOD/s4c1/*"
        ]
        }
      },
      "version": "1.1.0"
    }'

namespace: grs

hdiimage: docker-registry1.d6c9019.kyma-stage.shoot.live.k8s-hana.ondemand.com/kymahdigr
capimage: docker-registry1.d6c9019.kyma-stage.shoot.live.k8s-hana.ondemand.com/kymademogr
uiimage: docker-registry1.d6c9019.kyma-stage.shoot.live.k8s-hana.ondemand.com/kymademouigr

capapp: https://gr-kymacap.d6c9019.kyma-stage.shoot.live.k8s-hana.ondemand.com
uiapp: gr-approuterkymaui.d6c9019.kyma-stage.shoot.live.k8s-hana.ondemand.com

gitusername: c2hhbmthcmkuZy5yQHNhcC5jb20=
gitpassword: ZjhlMWY5MjhkNGZhOGQ2NWYwZGNmYTdiODJlMWZmZTI3YjMwODBkMw==
giturl: https://github.tools.sap/refapps/kyma-cap-s4ems.git
gitbranch: kyma-onpremise

functionshttpproxy: https://connectivity-proxy.cc:20003
functionsenv: '{ "name":"s4h", "attachmentSrvApi":"API_CV_ATTACHMENT_SRV", "businessPartnerSrvApi":"API_BUSINESS_PARTNER", "businessObjectTypeName" : "BUS1006" }'