apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: test-connectivity
  namespace: grs
spec:
  serviceOfferingName: connectivity
  servicePlanName: connectivity_proxy
  externalName: connectivity_proxy-instance

---

apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceBinding
metadata:
  name: test-connectivity-binding
  namespace: grs
spec:
  serviceInstanceName: test-connectivity
  externalName: test-connectivity-binding
  secretName: test-connectivity-binding
